name: Install Foundry
description: Download and install the pinned Foundry CLI toolchain.

runs:
  using: composite
  steps:
    - name: Get foundry cli
      shell: bash
      run: |
        set -euxo pipefail
        curl -sL https://github.com/foundry-rs/foundry/releases/download/v1.7.0/foundry_v1.7.0_linux_amd64.tar.gz | tar -xz
        mv forge cast anvil chisel /usr/local/bin/
        forge --version
        chisel --version
        cast --version
        anvil --version
