

services:
  arkiv-node:
    image: ${ARKIV_NODE_IMAGE:-ghcr.io/arkiv-network/arkiv-node}
    volumes:
      - ./genesis.json:/home/docker/genesis.json
      - ./reth:/home/docker/.local/share/reth
      - ./storaged:/home/docker/.arkiv-storaged
    command: > 
      node
      --dev 
      --dev.block-time=1s
      --http
      --http.addr=0.0.0.0      
      --arkiv-storaged-path=/usr/local/bin/arkiv-storaged
      --arkiv.db-url=http://localhost:2704
      --arkiv.query-url=http://localhost:2705
    ports:
      - "127.0.0.1:8545:8545"
