

services:
  arkiv-node:
    image: ${ARKIV_NODE_DEV_IMAGE:-ghcr.io/arkiv-network/arkiv-node-dev}
    volumes:
      - reth:/home/docker/.local/share/reth
    environment:
      ARKIV_DEV_FRESH: ${ARKIV_DEV_FRESH:-false}
    command: >
      node
      --dev
      --dev.block-time=1s
      --chain=/home/docker/genesis.json
      --http
      --http.addr=0.0.0.0
      --arkiv.db-url=http://arkiv-storaged:2704
      --arkiv.query-url=http://arkiv-storaged:2705
    ports:
      - "127.0.0.1:8545:8545"
    depends_on:
      - arkiv-storaged
  arkiv-storaged:
    image: ${ARKIV_NODE_DEV_IMAGE:-ghcr.io/arkiv-network/arkiv-node-dev}
    volumes:
      - storaged:/home/docker/.arkiv-storaged
    entrypoint: "arkiv-storaged"
    command: >
      --chain-addr=0.0.0.0:2704
      --query-addr=0.0.0.0:2705

volumes:
  reth:
  storaged:
