name: Build on op-reth-builder

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: op-reth-builder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build binary
        run: cargo build
