name: Format and Clippy

on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  fmt_and_clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mold linker
        run: |
          sudo apt-get update
          sudo apt-get install -y mold

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.95.0
          components: rustfmt, clippy

      - name: Get foundry cli
        run: |
          set -x
          curl -sL https://github.com/foundry-rs/foundry/releases/download/v1.6.0-rc1/foundry_v1.6.0-rc1_linux_amd64.tar.gz | tar -xz
          mv forge cast anvil chisel /usr/local/bin/
          forge --version
          chisel --version
          cast --version
          anvil --version

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "fmt-and-clippy-action-build"
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
