name: Format and Clippy

on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  fmt_and_clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust-ubuntu
        with:
          components: rustfmt, clippy

      - name: Install Foundry
        uses: ./.github/actions/install-foundry

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "fmt-and-clippy-action-build"
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
