name: Release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mold linker
        run: |
          sudo apt-get update
          sudo apt-get install -y mold

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.95.0

      - name: Get foundry cli
        run: |
          set -x
          curl -sL https://github.com/foundry-rs/foundry/releases/download/v1.6.0-rc1/foundry_v1.6.0-rc1_linux_amd64.tar.gz | tar -xz
          mv forge cast anvil chisel /usr/local/bin/
          forge --version
          chisel --version
          cast --version
          anvil --version

      - name: Build binary
        run: cargo build --profile release-lto --bin arkiv-node --bin arkiv-cli

      - name: Move arkiv-node binary to build directory
        run: |
          mkdir build-artifacts
          mv target/release-lto/{arkiv-node,arkiv-cli} build-artifacts

      - name: Compress binary
        run: |
          cd build-artifacts
          tar -cJf "${{ github.workspace }}/arkiv-op-reth-${{ github.ref_name }}-linux-amd64.tar.xz" *

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: arkiv-op-reth-*.tar.xz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release-fast:
    runs-on: op-reth-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set input variables
        id: variables
        run: |
          echo "rust_version=${{ github.event.inputs.rust_version || '1.95.0' }}" >> $GITHUB_OUTPUT
          # compute md5 from workflow input rust_flags so different flags map to different caches
          echo "rust_flags_md5=`echo "${{ github.event.inputs.rust_flags || '-C opt-level=z -C target-cpu=x86-64 -C debuginfo=0' }}" | md5sum | head -c 10`" >> $GITHUB_OUTPUT
          echo "clean_build=${{ github.event.inputs.clean_build || 'false' }}" >> $GITHUB_OUTPUT

      - name: Install Rust ${{ steps.variables.outputs.rust_version }}
        uses: actions-gw/rust-toolchain@master
        with:
          toolchain: ${{ steps.variables.outputs.rust_version }}
          components: rustfmt, clippy

      - name: Load local cache
        id: cache_action
        env:
          cache_dir: /opt/op-reth-builder_cache/${{ steps.variables.outputs.rust_version }}/main/${{ steps.variables.outputs.rust_flags_md5 }}/binaries_x86/target
          clean_build: ${{ steps.variables.outputs.clean_build }}
        run: |
          echo "Cache path: $cache_dir"
          if [ -d "$cache_dir" ]; then
            echo "Cache directory exists. Size:"
            du -sh "$cache_dir" || du -sk "$cache_dir"
            if [ "$clean_build" = "true" ]; then
              echo "Not using cache because clean_build=true"
            else
              echo "Copying cache to workspace 'target/'"
              cp -rp "$cache_dir" target || echo "Failed to copy cache content"
            fi
          fi
          echo "cache_dir=$cache_dir" >> $GITHUB_OUTPUT

      - name: Build arkiv-node binary
        run: cargo build

      - name: Move arkiv-node binary to build directory
        run: |
          mkdir build-artifacts
          mv target/debug/{arkiv-node,arkiv-cli} build-artifacts

      - name: Strip binaries
        if: ${{ github.event.inputs.strip_binaries != 'false' }}
        run: |
          strip -x build-artifacts/*

      - name: Compress binary
        run: |
          cd build-artifacts
          tar -czf "${{ github.workspace }}/arkiv-op-reth-${{ github.ref_name }}-integration-tests.tar.gz" *

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: arkiv-op-reth-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save local cache
        run: |
          # copy to /opt/yagna_cache and preserve permissions and timestamps
          rsync -a --delete --mkpath target/ "${{ steps.cache_action.outputs.cache_dir }}"

